---
- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.7.0-openjdk
   - libselinux-python
   - libsemanage-python
  sudo: yes

- name: Download JBoss from jboss.org
  get_url: url=http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip dest=/opt/jboss-as-7.1.1.Final.zip
  sudo: yes

- name: Extract archive
  unarchive: dest=/usr/share src=/opt/jboss-as-7.1.1.Final.zip creates=/usr/share/jboss-as copy=no 
  sudo: yes

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as
  sudo: yes

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest=/usr/share/jboss-as/standalone/configuration/
  notify: restart jboss
  sudo: yes

- name: Add group "jboss"
  group: name=jboss
  sudo: yes

- name: Add user "jboss"
  user: name=jboss group=jboss home=/usr/share/jboss-as
  sudo: yes

- name: Change ownership of JBoss installation
  file: path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes
  sudo: yes

- name: Copy the init script
  copy: src=jboss-as-standalone.sh dest=/etc/init.d/jboss mode=0755
  sudo: yes

- name: Enable JBoss to be started at boot
  service: name=jboss state=started
  sudo: yes

- name: deploy iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  when: ansible_distribution_major_version != "7" 
  notify: restart iptables
  sudo: yes

- name: Ensure that firewalld is installed
  yum: name=firewalld state=present
  when: ansible_distribution_major_version == "7" 
  sudo: yes

- name: Ensure that firewalld is started
  service: name=firewalld state=started
  when: ansible_distribution_major_version == "7" 
  sudo: yes

- name: deploy firewalld rules
  firewalld: immediate=yes port={{ item }} state=enabled permanent=yes
  when: ansible_distribution_major_version == "7"
  with_items:
  - "{{ http_port }}/tcp"
  - "{{ https_port }}/tcp"
  sudo: yes


